### ISSUE TITLE
Doesn't work on ubuntu 22.04.1

### ISSUE THREAD

**Issue by RealFX-Code** [danielfvm/Show#20]
This tool is exactly what I'm looking for, but doesn't work.

I'm running ubuntu 22.04.1 with GNOME 42.4 on X11.

Does anyone knows why this doesn't work, or how to fix this?

Logs:
```
Show on  master is 📦 v0.0.0 via 🐍 v3.10.6 
❯ python3 src/show.py -m background -f 30 example/frag0.glsl
DEBUG:opengl:requiring modern OpenGL without any legacy features
DEBUG:opengl:opening window
DEBUG:opengl:changed window typehint to background
DEBUG:opengl:creating and binding the vertex array (VAO)
DEBUG:opengl:creating and binding the vertex buffer (VBO)
DEBUG:opengl:setting the vertex attributes
DEBUG:shader:creating the shader program
DEBUG:shader:compiling the GL_VERTEX_SHADER (GL_VERTEX_SHADER) shader
DEBUG:shader:compiling the GL_FRAGMENT_SHADER (GL_FRAGMENT_SHADER) shader
DEBUG:shader:linking shader program
DEBUG:shader:installing shader program into rendering state
DEBUG:shader:creating the shader program
DEBUG:shader:compiling the GL_VERTEX_SHADER (GL_VERTEX_SHADER) shader
DEBUG:shader:compiling the GL_FRAGMENT_SHADER (GL_FRAGMENT_SHADER) shader
ERROR:shader:b'0(8) : error C7533: global variable gl_FragColor is deprecated after version 120\n'
DEBUG:opengl:cleaning up buffer
DEBUG:opengl:cleaning up vertex array
DEBUG:opengl:terminating window context
DEBUG:shader:cleaning up shader program
DEBUG:shader:cleaning up shader program
```

Thanks in advance, rx.

EDIT: I made a pr that fixes this, https://github.com/danielfvm/Show/pull/21#issue-1399561857
